### PR TITLE
Change styling and layout of UI

### PR DESCRIPTION
**Pull request by rizcheldayao**
Changing styling and layout of UI:
- Add scss package
- Add scss and css files with styling changes
- Edit index.html
- Add responsive design (i.e. it works on all devices)
- Add es6 support and babel

Working with @pwplusnick to iterate on designs for sign off 

Current design changes in two screenshots (in progress): 
screen shot 2018-01-16 at 5 29 29 pm
screen shot 2018-01-16 at 5 29 32 pm

### CODE REVIEW

**Comment by eggshell** [comment]
+1 Looks *MUCH* better!

**Comment by rizcheldayao** [comment]
@eggshell thanks! Open to feedback so let me know if there's anything you'd like changed or what not

**Comment by rizcheldayao** [comment]
@pwplusnick could you review and sign off? Since our call, I've fixed the animations, updated the dark mode to what we spoke about and removed "or architected" in related links

**Comment by pwplusnick** [comment]
👍 lgtm

**Pull request merged**
